### ISSUE TITLE
SCRIPT ERROR: @fivem-mysql/lib/MySQL.lua:219

### ISSUE THREAD

**Issue by youngbankhss** [ThymonA/fivem-mysql#3]
SCRIPT ERROR: @fivem-mysql/lib/MySQL.lua:219: Callback must be a function
![screenshot 50](https://user-images.githubusercontent.com/35543781/105522166-798b5880-5d0f-11eb-869b-5cb7c2d28058.jpg)

**Comment by ThymonA** [comment]
You're executing `MySQL.Async.execute` where given `callback` isn't a function. Isn't a `fivem-mysql` issue.
