### ISSUE TITLE
[Error] No such export ... in resource fivem-mysql

### ISSUE THREAD

**Issue by Azael-Dev** [ThymonA/fivem-mysql#4]
Error
```
No such export ... in resource fivem-mysql
 ```
I followed your advice: [Makes it easy to transform `fivem-mysql-async` to `fivem-mysql`](https://github.com/ThymonA/fivem-mysql/blob/master/lib/MySQL.lua#L3)

**Comment by ThymonA** [comment]
Did you download an release version or `master`?

**Comment by Azael-Dev** [comment]
> Did you download an release version or `master`?

Master

**Comment by ThymonA** [comment]
You should download a `release` version that's is already build or you need to build `master` yourself.

**How to build master?**
You clone `ThymonA/fivem-mysql` repo and `cd` into the cloned folder.
Then you need to type `npm init` to load all the nodejs dependencies required to build the project.
After those dependencies are installed/download, you need to execute `npx webpack` (to build the project).
When `npx webpack` has been finished, you can copy the following files:
- `build/fivemsql.js`
- `fxmanifest.lua`
- `lib/MySQL.lua`
- `LICENSE`
- `MySQL.lua`

If you want to have `fivemsql.js` in the root folder of your resource, you also need to change the `fxmanifest.lua`.

I hope this will help you, also `Release` should almost be the same as `master`

**Comment by Azael-Dev** [comment]
> คุณควรดาวน์โหลด`release`เวอร์ชันที่สร้างไว้แล้วหรือต้องสร้าง`master`เอง
> 
> **จะสร้างต้นแบบได้อย่างไร? **
> คุณโคลน`ThymonA/fivem-mysql`repo และ`cd`เข้าไปในโฟลเดอร์โคลน
> จากนั้นคุณต้องพิมพ์`npm init`เพื่อโหลดการอ้างอิง nodejs ทั้งหมดที่จำเป็นในการสร้างโครงการ
> หลังจากติดตั้ง / ดาวน์โหลดการอ้างอิงเหล่านั้นแล้วคุณต้องดำเนินการ`npx webpack`(เพื่อสร้างโครงการ)
> เมื่อ`npx webpack`เสร็จแล้วคุณสามารถคัดลอกไฟล์ต่อไปนี้:
> 
> * `build/fivemsql.js`
> * `fxmanifest.lua`
> * `lib/MySQL.lua`
> * `LICENSE`
> * `MySQL.lua`
> 
> หากคุณต้องการมี`fivemsql.js`ในโฟลเดอร์รูทของทรัพยากรของคุณคุณต้องเปลี่ยนไฟล์`fxmanifest.lua`.
> 
> ฉันหวังว่านี่จะช่วยคุณได้และก็`Release`เกือบจะเหมือนกับ`master`

Thank you for your advice.
