### ISSUE TITLE
SQL Syntax errors when using fivem-mysql

### ISSUE THREAD

**Issue by Vicken52** [ThymonA/fivem-mysql#5]
I'm seeing these following errors across all of my resources when trying to startup fxserver with fivem-mysql:
![image](https://user-images.githubusercontent.com/7284177/115602687-0e144100-a294-11eb-869e-c89938cc408f.png)

I updated all the resource.lua files with the following changes 
![image](https://user-images.githubusercontent.com/7284177/115603067-8f6bd380-a294-11eb-9da5-76f61f8a5636.png)
Is there more that needs to be done to migrate from mysql-async to fivem-mysql that I might be missing?

**Comment by ThymonA** [comment]
Thanks for reporting this issue, it doesn't seems like it compatible anymore.
The differents between those two are the way templates works.
I will fix this in the feature, but for know I recommand to use `mysql-async` if you already using it.

**mysql-async**
```lua
--- Example `players`
MySQL.Async.fetchAll('SELECT * FROM `players` WHERE `identifier` = @identifier', {
    ['@identifier'] = 'steam:...'
}, function(results)
    print(json.encode(results))
end)
```
**fivem-mysql**
```lua
--- Example `players`
MySQL.Async.fetchAll('SELECT * FROM `players` WHERE `identifier` = :identifier', {
    ['identifier'] = 'steam:...'
}, function(results)
    print(json.encode(results))
end)

--- OR

mysql:fetchAllAsync('SELECT * FROM `players` WHERE `identifier` = :identifier', {
    ['identifier'] = 'steam:...'
}, function(results)
    print(json.encode(results))
end)
```

**Comment by Vicken52** [comment]
I'll keep using `mysql-async` and wait for the fix before migrating over, thank you so much!
